[project]
name = "jira"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "email-reply-parser>=0.5.12",
    "requests>=2.32.5",
]
